=== mark-burnett/filament-dynamics/data/xml/dtd/parameter_set_groups.dtd
<!ELEMENT parameter_set_groups (parameter_set_group*)>
<!ELEMENT parameter_set_group (parameter_set*)>
    <!ATTLIST parameter_set_group name CDATA #REQUIRED>
    <!ATTLIST parameter_set_group simulation_name CDATA #REQUIRED>
    <!ATTLIST parameter_set_group description CDATA #IMPLIED>

<!ELEMENT parameter_set (parameter*)>
    <!ATTLIST parameter_set name CDATA #IMPLIED>
    <!ATTLIST parameter_set description CDATA #IMPLIED>

<!ELEMENT parameter EMPTY>
    <!ATTLIST parameter parameter_label_name CDATA #REQUIRED>
    <!ATTLIST parameter value CDATA #REQUIRED>

=== mark-burnett/filament-dynamics/data/xml/parameter_set_groups/random_polymerization_fujiwara.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE parameter_set_groups SYSTEM '../dtd/parameter_set_groups.dtd'>

<parameter_set_groups>
    <parameter_set_group
        name='Typical Parameters'
        description='Some typical parameters from the literature.'
        simulation_name='Random Model - Polymerization Timecourse'>
        <parameter_set
            name='Fujiwara -> Pollard Experiment'
            description='Fujiwara model parameters, Pollard growth experiment.'>

            <!-- Polymerization/Depolymerization Rates -->
            <parameter
                parameter_label_name='Barbed ATP Polymerization Rate'
                value='11.6'/>
            <parameter
                parameter_label_name='Barbed ATP Depolymerization Rate'
                value='1.4'/>

            <parameter
                parameter_label_name='Barbed ADP-Pi Polymerization Rate'
                value='3.4'/>
            <parameter
                parameter_label_name='Barbed ADP-Pi Depolymerization Rate'
                value='0.2'/>

            <parameter
                parameter_label_name='Barbed ADP Polymerization Rate'
                value='2.9'/>
            <parameter
                parameter_label_name='Barbed ADP Depolymerization Rate'
                value='5.4'/>

            <!-- Hydrolysis Rates -->
            <parameter
                parameter_label_name='Cleavage Rate'
                value='0.3'/>
            <parameter
                parameter_label_name='Release Rate'
                value='0.003'/>
            <parameter
                parameter_label_name='Release Rate In Solution'
                value='20'/>

            <!-- Concentrations -->
            <parameter
                parameter_label_name='Filament Tip Concentration'
                value='0.0112'/>
            <parameter
                parameter_label_name='Seed Concentration'
                value='6'/>

            <parameter
                parameter_label_name='Initial ATP Concentration'
                value='6'/>
            <parameter
                parameter_label_name='Initial ADP-Pi Concentration'
                value='0'/>
            <parameter
                parameter_label_name='Initial ADP Concentration'
                value='0'/>

            <parameter
                parameter_label_name='Initial Pi Concentration'
                value='0'/>

            <!-- Misc. Parameters -->
            <parameter
                parameter_label_name='Simulation Duration'
                value='40'/>

        </parameter_set>
    </parameter_set_group>
</parameter_set_groups>
