=== mark-burnett/filament-dynamics/data/xml/dtd/parameter_labels.dtd
<!ELEMENT parameter_labels (parameter_label*)>
<!ELEMENT parameter_label EMPTY>
    <!ATTLIST parameter_label name CDATA #REQUIRED>
    <!ATTLIST parameter_label description CDATA #IMPLIED>

=== mark-burnett/filament-dynamics/data/xml/parameter_labels.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE parameter_labels SYSTEM 'dtd/parameter_labels.dtd'>

<parameter_labels>
    <!-- Concentration Labels -->
    <parameter_label
        name='ATP Concentration'
        description='Concentration of ATP in solution.'/>

    <parameter_label
        name='ADP Concentration'
        description='Concentration of ADP in solution.'/>

    <parameter_label
        name='Initial ATP Concentration'
        description='Initial concentration of ATP in solution.'/>

    <parameter_label
        name='Initial ADP Concentration'
        description='Initial concentration of ADP in solution.'/>

    <parameter_label
        name='Initial Pi Concentration'
        description='Initial concentration of phosphate in solution.'/>



    <!-- Hydrolysis Transition Rates -->
    <parameter_label
        name='Cleavage Rate'
        description='Rate of phosphate cleavage.'/>

    <parameter_label
        name='Release Rate'
        description='Rate of phosphate release.'/>


    <!-- Polymerization/Depolymerization Transition Rates -->
    <parameter_label
        name='Barbed ATP Polymerization Rate'
        description='Rate of ATP polymerization at barbed end.'/>

    <parameter_label
        name='Barbed ADP Polymerization Rate'
        description='Rate of ADP polymerization at barbed end.'/>

    <parameter_label
        name='Barbed ADP-Pi Polymerization Rate'
        description='Rate of ADP-Pi polymerization at barbed end.'/>

    <parameter_label
        name='Pointed ATP Polymerization Rate'
        description='Rate of ATP polymerization at pointed end.'/>

    <parameter_label
        name='Pointed ADP Polymerization Rate'
        description='Rate of ADP polymerization at pointed end.'/>

    <parameter_label
        name='Pointed ADP-Pi Polymerization Rate'
        description='Rate of ADP-Pi polymerization at pointed end.'/>


    <parameter_label
        name='Barbed ATP Depolymerization Rate'
        description='Rate of ATP depolymerization at barbed end.'/>

    <parameter_label
        name='Barbed ADP Depolymerization Rate'
        description='Rate of ADP depolymerization at barbed end.'/>

    <parameter_label
        name='Barbed ADP-Pi Depolymerization Rate'
        description='Rate of ADP-Pi depolymerization at barbed end.'/>

    <parameter_label
        name='Pointed ATP Depolymerization Rate'
        description='Rate of ATP depolymerization at pointed end.'/>

    <parameter_label
        name='Pointed ADP Depolymerization Rate'
        description='Rate of ADP depolymerization at pointed end.'/>

    <parameter_label
        name='Pointed ADP-Pi Depolymerization Rate'
        description='Rate of ADP-Pi depolymerization at pointed end.'/>


    <!-- Misc. Parameters -->
    <parameter_label
        name='Initial Strand Length'
        description='Initial length of the strand.'/>

    <parameter_label
        name='Simulation Duration'
        description='Time to run the simulation.'/>

    <parameter_label
        name='Filament Tip Concentration'
        description='Concentration of filaments.'/>
</parameter_labels>
