=== mark-burnett/filament-dynamics/data/xml/dtd/simulations.dtd
<!ELEMENT simulations (simulation*)>
    <!ELEMENT simulation (strand_factory, concentrations, end_conditions,
                          explicit_measurements, transitions)>
        <!ATTLIST simulation name CDATA #REQUIRED>
        <!ATTLIST simulation description CDATA #IMPLIED>


<!ELEMENT binding (parameter_mappings, state_mappings)>
    <!ATTLIST binding class_name CDATA #REQUIRED>

<!ELEMENT parameter_mappings (parameter_mapping*)>
<!ELEMENT parameter_mapping EMPTY>
    <!ATTLIST parameter_mapping parameter_label_name CDATA #REQUIRED>
    <!ATTLIST parameter_mapping local_name CDATA #REQUIRED>

<!ELEMENT state_mappings (state_mapping*)>
<!ELEMENT state_mapping EMPTY>
    <!ATTLIST state_mapping state_name CDATA #REQUIRED>
    <!ATTLIST state_mapping local_name CDATA #REQUIRED>


<!ELEMENT strand_factory (binding)>

<!ELEMENT concentrations (concentration*)>
    <!ELEMENT concentration (binding)>
        <!ATTLIST concentration state_name CDATA #REQUIRED>
        <!ATTLIST concentration measurement_label_name CDATA #IMPLIED>

<!ELEMENT end_conditions (end_condition)>
    <!ELEMENT end_condition (binding)>

<!ELEMENT explicit_measurements (explicit_measurement)>
    <!ELEMENT explicit_measurement (binding)>
        <!ATTLIST explicit_measurement measurement_label_name CDATA #REQUIRED>

<!ELEMENT transitions (transition*)>
    <!ELEMENT transition (binding)>
        <!ATTLIST transition name CDATA #REQUIRED>
        <!ATTLIST transition measurement_label_name CDATA #IMPLIED>

=== mark-burnett/filament-dynamics/data/xml/simulations/full_random.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE simulations SYSTEM '../dtd/simulations.dtd'>

<simulations>
    <simulation
        name='Random Model - Polymerization Timecourse'
        description='Fully random model polymerized with limited reagents.'>

        <!-- Initial strand setup -->
        <strand_factory>
            <binding class_name='SingleState'>
                <parameter_mappings>
                    <parameter_mapping
                        parameter_label_name='Initial Strand Length'
                        local_name='length'/>
                </parameter_mappings>

                <state_mappings>
                    <state_mapping
                        state_name='ADP'
                        local_name='state'/>
                </state_mappings>
            </binding>
        </strand_factory>


        <!-- Concentrations -->
        <concentrations>
            <concentration
                state_name='ATP'
                measurement_label_name='ATP Actin Concentration'>

                <binding class_name='FixedReagent'>
                    <parameter_mappings>
                        <parameter_mapping
                            parameter_label_name='Initial ATP Concentration'
                            local_name='initial_concentration'/>
                        <parameter_mapping
                            parameter_label_name='Filament Tip Concentration'
                            local_name='filament_tip_concentration'/>
                    </parameter_mappings>

                    <state_mappings>
                    </state_mappings>
                </binding>
            </concentration>

            <concentration
                state_name='ADP'
                measurement_label_name='ADP Actin Concentration'>

                <binding class_name='FixedReagent'>
                    <parameter_mappings>
                        <parameter_mapping
                            parameter_label_name='Initial ADP Concentration'
                            local_name='initial_concentration'/>
                        <parameter_mapping
                            parameter_label_name='Filament Tip Concentration'
                            local_name='filament_tip_concentration'/>
                    </parameter_mappings>

                    <state_mappings>
                    </state_mappings>
                </binding>
            </concentration>

            <concentration
                state_name='Pi'
                measurement_label_name='Phosphate Concentration'>

                <binding class_name='FixedReagent'>
                    <parameter_mappings>
                        <parameter_mapping
                            parameter_label_name='Initial Pi Concentration'
                            local_name='initial_concentration'/>
                        <parameter_mapping
                            parameter_label_name='Filament Tip Concentration'
                            local_name='filament_tip_concentration'/>
                    </parameter_mappings>

                    <state_mappings>
                    </state_mappings>
                </binding>
            </concentration>

        </concentrations>


        <!-- End Conditions -->
        <end_conditions>
            <end_condition>
                <binding class_name='Duration'>
                    <parameter_mappings>
                        <parameter_mapping
                            parameter_label_name='Simulation Duration'
                            local_name='duration'/>
                    </parameter_mappings>

                    <state_mappings>
                    </state_mappings>
                </binding>
            </end_condition>

        </end_conditions>


        <!-- Explicit Measurements -->
        <explicit_measurements>
            <explicit_measurement
                measurement_label_name='Strand Length'>

                <binding class_name='StrandLength'>
                    <parameter_mappings>
                    </parameter_mappings>

                    <state_mappings>
                    </state_mappings>
                </binding>
            </explicit_measurement>

        </explicit_measurements>


        <!-- Transitions -->
        <transitions>
            <transition
                name='Cleavage'
                measurement_label_name='Cleavage Count'>

                <binding class_name='RandomHydrolysis'>
                    <parameter_mappings>
                        <parameter_mapping
                            parameter_label_name='Cleavage Rate'
                            local_name='rate'/>
                    </parameter_mappings>

                    <state_mappings>
                        <state_mapping
                            state_name='ATP'
                            local_name='old_state'/>
                        <state_mapping
                            state_name='ADP-Pi'
                            local_name='new_state'/>
                    </state_mappings>
                </binding>
            </transition>

            <transition
                name='Release'
                measurement_label_name='Release Count'>

                <binding class_name='RandomHydrolysisWithByproduct'>
                    <parameter_mappings>
                        <parameter_mapping
                            parameter_label_name='Release Rate'
                            local_name='rate'/>
                    </parameter_mappings>

                    <state_mappings>
                        <state_mapping
                            state_name='ADP-Pi'
                            local_name='old_state'/>
                        <state_mapping
                            state_name='Pi'
                            local_name='byproduct'/>
                        <state_mapping
                            state_name='ADP'
                            local_name='new_stae'/>
                    </state_mappings>
                </binding>
            </transition>

            <transition
                name='Barbed ATP Polymerization'
                measurement_label_name='Barbed ATP Polymerization Count'>

                <binding class_name='BarbedPolymerization'>
                    <parameter_mappings>
                        <parameter_mapping
                            parameter_label_name='ATP Polymerization Rate'
                            local_name='rate'/>
                    </parameter_mappings>

                    <state_mappings>
                        <state_mapping
                            state_name='ATP'
                            local_name='state'/>
                    </state_mappings>
                </binding>
            </transition>

            <transition
                name='Barbed ADP Polymerization'
                measurement_label_name='Barbed ADP Polymerization Count'>

                <binding class_name='BarbedPolymerization'>
                    <parameter_mappings>
                        <parameter_mapping
                            parameter_label_name='ADP Polymerization Rate'
                            local_name='rate'/>
                    </parameter_mappings>

                    <state_mappings>
                        <state_mapping
                            state_name='ADP'
                            local_name='state'/>
                    </state_mappings>
                </binding>
            </transition>

            <transition
                name='Barbed ATP Depolymerization'
                measurement_label_name='Barbed ATP Depolymerization Count'>

                <binding class_name='BarbedDepolymerization'>
                    <parameter_mappings>
                        <parameter_mapping
                            parameter_label_name='ATP Depolymerization Rate'
                            local_name='rate'/>
                    </parameter_mappings>

                    <state_mappings>
                        <state_mapping
                            state_name='ATP'
                            local_name='state'/>
                    </state_mappings>
                </binding>
            </transition>

            <transition
                name='Barbed ADP Depolymerization'
                measurement_label_name='Barbed ADP Depolymerization Count'>

                <binding class_name='BarbedDepolymerization'>
                    <parameter_mappings>
                        <parameter_mapping
                            parameter_label_name='ADP Depolymerization Rate'
                            local_name='rate'/>
                    </parameter_mappings>

                    <state_mappings>
                        <state_mapping
                            state_name='ADP'
                            local_name='state'/>
                    </state_mappings>
                </binding>
            </transition>

        </transitions>
    </simulation>
</simulations>
